# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-24 16:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acchievemnts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='اذكر باختصار أهم انجازاتك المهنية')),
            ],
        ),
        migrations.CreateModel(
            name='CloseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_contacts_Name', models.CharField(default='', max_length=200, verbose_name='الاسم')),
                ('close_contacts_residence_place', models.CharField(default='', max_length=200, verbose_name='عنوان السكن')),
                ('close_contacts_relation', models.CharField(default='', max_length=200, verbose_name='نوع القرابة')),
                ('close_contacts_phone', models.CharField(default='', max_length=200, verbose_name='رقم الهاتف')),
                ('close_contacts_other_phone', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم أخر')),
                ('close_contacts_job', models.CharField(default='', max_length=200, verbose_name='العمل')),
                ('close_contacts_work_address', models.CharField(default='', max_length=200, verbose_name='عنوان العمل')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_knowledge', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تستطيع استخدام الحاسب الآلي')),
                ('computer_knowledge_details', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نرجو تحديد أسماء البرامج')),
                ('internet_knowledge', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تستطيع استخدام البريد الإلكتروني')),
                ('internet_knowledge_details', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نرجو تحديد أنواع البريد')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_Name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='اسم الدورة')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الفترة من')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الفترة إلى')),
                ('palce', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الجهة المنفذة للدورة')),
                ('country', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الدولة')),
                ('cert_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التخصص')),
                ('interval', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عدد الساعات')),
                ('score', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التقدير العام')),
                ('specialization', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التخصص')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_license', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تستطيع قيادة السيارات وسائل النقل')),
                ('driving_license_active', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, null=True, verbose_name='هل لديك رخصة قيادة سارية المفعول')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_type', models.CharField(choices=[('T', 'Toefel'), ('en', 'امتحان أخر باللغة الانجليزية'), ('o', 'امتحان أخر بلغة أخرى')], default='', max_length=100, null=True, verbose_name='هل سبق وتقدمت لامتحان اللغة')),
                ('ex_score', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='التقدير العام')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='أسم المنشأة وعنوانها')),
                ('position1_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 1')),
                ('position1_from_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ')),
                ('position1_to_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ')),
                ('position2_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 2')),
                ('position2_from_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ')),
                ('position2_to_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ')),
                ('position3_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 3')),
                ('position3_from_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ')),
                ('position3_to_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ')),
                ('resp_desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='وصف مختصر للمهام والواجبات والمسؤوليات لأخر وظيفة')),
                ('join_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ الالتحاق بالعمل')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ انتهاء الخدمة')),
                ('salary_begin', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الراتب الشهري عند التوظيف')),
                ('salary_end', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الراتب الشهري عند انتهاء الخدمة')),
                ('allowance', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='العلاوات الأخرى بالتفصيل')),
                ('last_supervison', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='اسم أخر رئيس مباشر عليك')),
                ('last_supervison_phone', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم هاتفه')),
                ('end_service_reason', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='أسباب انتهاء الخدمة')),
            ],
        ),
        migrations.CreateModel(
            name='Inqueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inq_loan', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل عليك قروض أو ديون أو مشاكل مادية')),
                ('inq_training', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك')),
                ('inq_training_detail', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة ب )نعم( نرجو تحديد هذه الدورات')),
                ('inq_long_term_disease', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تعاني من أي مشاكل صحية أو نفسية أو أمراض مزمنة')),
                ('inq_long_term_disease_detail', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة ب )نعم( نرجو ذكرها')),
                ('inq_surgery', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل سبق ان أجريت لك أي عملية جراحية')),
                ('inq_cust_contact', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل سبق وكانت طبيعة عملك تتطلب التعامل مع العملاء؟')),
                ('inq_favor_w_place', models.IntegerField(blank=True, choices=[(23, 'الأمانة'), (1, 'عمران'), (2, 'محافظة صنعاء'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], default='0', verbose_name='ماهي المحافظة التي تفضل العمل فيها، بحكم تواجد السكن الأصلي لك؟')),
                ('inq_accept_w_place', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, verbose_name='وهل تقبل العمل في محافظة إذا طلب منك ذلك')),
                ('inq_explain', models.TextField(default='', max_length=200, verbose_name='لماذا ترغب في العمل لدى البنك المركزي اليمني؟')),
            ],
        ),
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='الاسم الأول')),
                ('father_name', models.CharField(max_length=200, verbose_name='اسم الأب')),
                ('grandfather_name', models.CharField(max_length=200, verbose_name='اسم الجد')),
                ('surname', models.CharField(max_length=200, verbose_name='اللقب:')),
                ('birth_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الميلاد ')),
                ('birth_place', models.CharField(max_length=200, verbose_name='مكان الميلاد')),
                ('nationality', models.CharField(choices=[('Y', 'يمني'), ('O', 'أخرى')], max_length=200, verbose_name='الجنسية')),
                ('blood_type', models.CharField(blank=True, choices=[('A1', 'A+'), ('A2', 'A-'), ('B1', 'B+'), ('B2', 'B-'), ('AB1', 'AB+'), ('AB2', 'AB-'), ('O1', 'O+'), ('O2', 'O-')], max_length=200, null=True, verbose_name='فصيلة الدم')),
                ('father_birth_place', models.CharField(max_length=200, verbose_name='مكان ميلاد الأب')),
                ('ID_type', models.CharField(choices=[('ID', 'بطاقة شخصية'), ('PS', 'جوازسفر'), ('O', 'أخرى')], max_length=200, verbose_name='نوع الهوية')),
                ('ID_issued_from', models.CharField(max_length=200, verbose_name='صادرة من')),
                ('ID_number', models.CharField(max_length=200, verbose_name='برقم')),
                ('ID_issue_date', models.DateField(default=datetime.date.today, verbose_name='وبتاريخ')),
                ('marital_status', models.CharField(choices=[('S', 'عازب'), ('M', 'متزوج'), ('O', 'أخرى')], max_length=200, verbose_name='الحالة الإجتماعية')),
                ('childs_number', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عدد الأولاد')),
                ('mobile', models.CharField(max_length=200, verbose_name='رقم هاتفك المحمول')),
                ('mobile_other', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم أخر')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='البريد الإلكتروني')),
                ('email_other', models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='أخر')),
                ('Hobbies', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='الهوايات')),
                ('residence_place', models.CharField(blank=True, db_column=False, max_length=100, null=True, verbose_name='عنوان السكن الدائم')),
                ('residence_city', models.IntegerField(choices=[(23, 'الأمانة'), (1, 'عمران'), (2, 'محافظة صنعاء'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], verbose_name='المحافظة')),
                ('residence_district', models.CharField(default='', max_length=200, verbose_name='بجوار أو بالقرب ')),
                ('residence_street', models.CharField(default='', max_length=200, verbose_name='الحي أو الشارع')),
                ('home_phone', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم هاتف المنزل')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حساب واتساب')),
                ('telegram', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حساب التليجرام')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استمارة طلب توظيف',
            },
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_fit_name', models.CharField(default='', max_length=200, verbose_name='الوظيفة التي تقدمت لشغلها و التي تتناسب مع مؤهلك')),
                ('job_know_channel', models.CharField(default='', max_length=200, verbose_name='كيف علمت بهذه الوظيفة')),
                ('job_salary_exp', models.CharField(default='', max_length=100, verbose_name='الراتب والمزايا المتوقعة')),
                ('job_favorite_hours', models.CharField(default='', max_length=200, verbose_name='ساعات العمل التي تفضلها')),
                ('job_non_announcement', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حدد وضيفة أخرى معلن عنها وترغب بالتقدم لها وتعتقد أنك مؤهل لها عدا الوظيفة المتقدم لها')),
                ('job_least_income', models.CharField(default='', max_length=200, verbose_name='ما هو أقل دخل شهري يمكنك العمل به شاملاً جميع البدلات')),
                ('job_in_bank_relat', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل لديك أقارب في البنك المركزي اليمني')),
                ('job_in_bank_relat_desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة بنعم – نرجو تحديد اسم وصلة الشخص')),
                ('job_out_bank_relat', models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل لديك أقارب في الجهات ذات الصلة بالبنك')),
                ('job_out_bank_relat_desc', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة بنعم – نرجو تحديد اسم الجهة واسم وصلة الشخص')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp')),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_type', models.CharField(choices=[('en', 'الإنجليزية'), ('ar', 'العربية'), ('o', 'اخرى')], default='', max_length=200, verbose_name='اللغة')),
                ('conv_level', models.CharField(blank=True, choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, null=True, verbose_name='محادثة')),
                ('writing_level', models.CharField(blank=True, choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, null=True, verbose_name='كتابة')),
                ('reading_level', models.CharField(blank=True, choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, null=True, verbose_name='قراءة')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=' ')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name=' ')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name=' ')),
                ('experience', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clfy_name', models.CharField(blank=True, choices=[('s', 'الثانوية'), ('id', 'دبلوم متوسط'), ('b', 'بكالوريوس'), ('hd', 'دبلوم عالي'), ('m', 'ماجيستير'), ('phd', 'دكتوراه'), ('o', 'اخرى')], default='', max_length=100, null=True, verbose_name='المؤهل الدراسي')),
                ('clfy_from_date', models.DateField(default=datetime.date.today, verbose_name='من')),
                ('clfy_to_date', models.DateField(default=datetime.date.today, verbose_name='إلى')),
                ('clfy_place', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='اسم المدرسة/الجامعة')),
                ('clfy_country', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='الدولة')),
                ('clfy_type', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='التخصص')),
                ('clfy_graduate_date', models.DateField(default=datetime.date.today, verbose_name='سنة التخرج')),
                ('clfy_ranking', models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='التقدير العام')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.JobApp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='هل سبق وتقدمت اللغة')),
                ('y', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='التقدير العام')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='الرجاء تحديد أي مهارات/قدرات خاصة بك')),
                ('job', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp')),
            ],
        ),
        migrations.AddField(
            model_name='inqueries',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='exam',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='courses',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='computerknowledge',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='closecontact',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp', verbose_name=' '),
        ),
        migrations.AddField(
            model_name='acchievemnts',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp', verbose_name=' '),
        ),
    ]
