# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('grandfather_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(choices=[('Y', 'Yemeni'), ('O', 'Other')], max_length=200)),
                ('blood_type', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'AB'), ('4', 'O')], max_length=200)),
                ('father_birth_place', models.CharField(choices=[('Y', 'Yemeni'), ('O', 'Other')], max_length=200)),
                ('ID_type', models.CharField(choices=[('ID', 'ID'), ('PS', 'Passport'), ('oO', 'Other')], max_length=200)),
                ('ID_issued_from', models.CharField(max_length=200)),
                ('ID_number', models.CharField(max_length=200)),
                ('ID_issue_date', models.DateField()),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('O', 'Other')], max_length=200)),
                ('childs_number', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('mobile_other', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Hobbies', models.CharField(max_length=200)),
                ('residence_place', models.CharField(max_length=200)),
                ('residence_city', models.CharField(max_length=200)),
                ('residence_district', models.CharField(max_length=200)),
                ('residence_street', models.CharField(max_length=200)),
                ('home_phone', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('close_contacts_1_Name', models.CharField(max_length=200)),
                ('close_contacts_1_residence_place', models.CharField(max_length=200)),
                ('close_contacts_1_relation', models.CharField(max_length=200)),
                ('close_contacts_1_phone', models.CharField(max_length=200)),
                ('close_contacts_1_other_phone', models.CharField(max_length=200)),
                ('close_contacts_1_job', models.CharField(max_length=200)),
                ('close_contacts_1_work_address', models.CharField(max_length=200)),
                ('close_contacts_2_Name', models.CharField(max_length=200)),
                ('close_contacts_2_residence_place', models.CharField(max_length=200)),
                ('close_contacts_2_relation', models.CharField(max_length=200)),
                ('close_contacts_2_phone', models.CharField(max_length=200)),
                ('close_contacts_2_other_phone', models.CharField(max_length=200)),
                ('close_contacts_2_job', models.CharField(max_length=200)),
                ('close_contacts_2_work_address', models.CharField(max_length=200)),
            ],
        ),
    ]
