# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='inq_explain',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='لماذا ترغب في العمل لدى البنك المركزي اليمني؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_loan',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, null=True, verbose_name='هل عليك قروض أو ديون أو مشاكل مادية'),
        ),
    ]
