# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='specialization',
        ),
        migrations.AddField(
            model_name='inqueries',
            name='inq_surgery_detail',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='عند الإجابة بنعم - نرجو تحديدها'),
        ),
        migrations.AlterField(
            model_name='computerknowledge',
            name='computer_knowledge_details',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عند الإجابة بنعم نرجو تحديد أسماء البرامج'),
        ),
        migrations.AlterField(
            model_name='computerknowledge',
            name='internet_knowledge_details',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عند الإجابة بنعم نرجو تحديد أسماء البريد'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ex_type',
            field=models.CharField(choices=[('T', 'Toefel'), ('en', 'امتحان أخر باللغة الانجليزية'), ('o', 'امتحان أخر بلغة أخرى')], default='', max_length=100, null=True, verbose_name='نوع الإختبار'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا'), ('NN', 'ليس الان')], default='', max_length=20, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training_detail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عند الإجابة بنعم - نرجو تحديدها'),
        ),
        migrations.AlterField(
            model_name='relatedlang',
            name='x',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نوع الإختبار'),
        ),
    ]
