# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201224_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='inq_surgery',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل سبق ان أجريت لك أي عملية جراحية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_surgery_detail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عند الإجابة بنعم - نرجو تحديدها'),
        ),
    ]
