# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201226_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='inq_accept_w_place',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], max_length=200, null=True, verbose_name='وهل تقبل العمل في محافظة إذا طلب منك ذلك'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_cust_contact',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], max_length=20, null=True, verbose_name='هل سبق وكانت طبيعة عملك تتطلب التعامل مع العملاء؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_explain',
            field=models.TextField(max_length=200, verbose_name='لماذا ترغب في العمل لدى البنك المركزي اليمني؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_loan',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], max_length=20, null=True, verbose_name='هل عليك قروض أو ديون أو مشاكل مادية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_long_term_disease',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], max_length=200, null=True, verbose_name='هل تعاني من أي مشاكل صحية أو نفسية أو أمراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_surgery',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], max_length=200, null=True, verbose_name='هل سبق ان أجريت لك أي عملية جراحية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا'), ('NN', 'ليس الان')], max_length=20, null=True, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك'),
        ),
    ]
