# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201226_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ex_type',
            field=models.CharField(blank=True, choices=[('T', 'Toefel'), ('en', 'امتحان أخر باللغة الانجليزية'), ('o', 'امتحان أخر بلغة أخرى'), ('NA', ' لا يوجد')], default='', max_length=100, null=True, verbose_name='نوع الإختبار'),
        ),
    ]
