# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201205_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acchievemnts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_contacts_Name', models.CharField(default='', max_length=200)),
                ('close_contacts_residence_place', models.CharField(default='', max_length=200)),
                ('close_contacts_relation', models.CharField(default='', max_length=200)),
                ('close_contacts_phone', models.CharField(default='', max_length=200)),
                ('close_contacts_other_phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('close_contacts_job', models.CharField(default='', max_length=200)),
                ('close_contacts_work_address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComputerKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_knowledge', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('internet_knowledge', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('courses_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('courses_3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('courses_4', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_license', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('driving_license_active', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('resp_desc', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary_begin', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('salary_end', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('allowance', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_supervison', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_supervison_phone', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('end_service_reason', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inqueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inq_loan', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20)),
                ('inq_training', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('D', 'Not Now')], default='', max_length=20)),
                ('inq_training_detail', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('inq_long_term_disease', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('inq_surgery', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('inq_cust_contact', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sometimes')], default='', max_length=20)),
                ('inq_favor_w_place', models.IntegerField(choices=[(1, 'Sanaa'), (2, 'Aden'), (3, 'IBB'), (4, 'Taiz'), (5, 'Thamar'), (6, 'Amran'), (7, 'Shabwa'), (8, 'Haja')], default='0')),
                ('inq_accept_w_place', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=200)),
                ('inq_explain', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_fit_name', models.CharField(default='', max_length=200)),
                ('job_know_channel', models.CharField(default='', max_length=200)),
                ('job_salary_exp', models.CharField(default='', max_length=200)),
                ('job_favorite_hours', models.CharField(default='', max_length=200)),
                ('job_non_announcement', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('job_least_income', models.CharField(default='', max_length=200)),
                ('job_in_bank_relat', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('job_out_bank_relat', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_ar', models.CharField(default='', max_length=200)),
                ('lang_en', models.CharField(default='', max_length=200)),
                ('lang_other1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lang_other2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lang_toefl', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lang_en_exam', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lang_lang_exam', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('grandfather_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(choices=[('Y', 'Yemeni'), ('O', 'Other')], max_length=200)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=200, null=True)),
                ('father_birth_place', models.CharField(max_length=200)),
                ('ID_type', models.CharField(choices=[('ID', 'ID'), ('PS', 'Passport'), ('O', 'Other')], max_length=200)),
                ('ID_issued_from', models.CharField(max_length=200)),
                ('ID_number', models.CharField(max_length=200)),
                ('ID_issue_date', models.DateField()),
                ('mobile', models.CharField(max_length=200)),
                ('mobile_other', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('email_other', models.EmailField(default='', max_length=100)),
                ('Hobbies', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('residence_place', models.CharField(default='', max_length=200)),
                ('residence_city', models.IntegerField(choices=[(1, 'Sanaa'), (2, 'Aden'), (3, 'IBB'), (4, 'Taiz'), (5, 'Thamar'), (6, 'Amran'), (7, 'Shabwa'), (8, 'Haja')], default='0')),
                ('residence_district', models.CharField(default='', max_length=200)),
                ('residence_street', models.CharField(default='', max_length=200)),
                ('home_phone', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('telegram', models.CharField(blank=True, default='0', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('from_dat', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clfy_secondary', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_inter_diplom', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_bechalore', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_high_diplom', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_master', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_phd', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clfy_other', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person')),
            ],
        ),
        migrations.AddField(
            model_name='lang',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='inqueries',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Position'),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='courses',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='computerknowledge',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='closecontact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
        migrations.AddField(
            model_name='acchievemnts',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Person'),
        ),
    ]
