# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201210_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='from_dat',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skills',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='experience',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.Experience'),
        ),
    ]
