# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-10 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201210_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position1_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position1_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position2_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position2_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position3_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position3_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ID_issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='person',
            name='ID_issue_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='position',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
