# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-11 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201210_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('grandfather_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('nationality', models.CharField(choices=[('Y', 'Yemeni'), ('O', 'Other')], max_length=200)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=200, null=True)),
                ('father_birth_place', models.CharField(max_length=200)),
                ('ID_type', models.CharField(choices=[('ID', 'ID'), ('PS', 'Passport'), ('O', 'Other')], max_length=200)),
                ('ID_issued_from', models.CharField(max_length=200)),
                ('ID_number', models.CharField(max_length=200)),
                ('ID_issue_date', models.DateField(default=datetime.date.today)),
                ('mobile', models.CharField(max_length=200)),
                ('mobile_other', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('email_other', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('Hobbies', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('residence_place', models.CharField(default='', max_length=200)),
                ('residence_city', models.CharField(choices=[(1, 'Sanaa'), (2, 'Aden'), (3, 'IBB'), (4, 'Taiz'), (5, 'Thamar'), (6, 'Amran'), (7, 'Shabwa'), (8, 'Haja')], max_length=200)),
                ('residence_district', models.CharField(default='', max_length=200)),
                ('residence_street', models.CharField(default='', max_length=200)),
                ('home_phone', models.CharField(blank=True, default='00967', max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, default='00967', max_length=200, null=True)),
                ('telegram', models.CharField(blank=True, default='00967', max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='acchievemnts',
            name='person',
        ),
        migrations.RemoveField(
            model_name='closecontact',
            name='person',
        ),
        migrations.RemoveField(
            model_name='computerknowledge',
            name='person',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='person',
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='person',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='person',
        ),
        migrations.RemoveField(
            model_name='inqueries',
            name='person',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='person',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='person',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='acchievemnt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Acchievemnts'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='computer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.ComputerKnowledge'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.CloseContact'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Courses'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='dlicense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.DrivingLicense'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='experience',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Experience'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='inquery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Inqueries'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.JobDetails'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='lang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Lang'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='qualification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Qualification'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.Skill'),
        ),
    ]
