# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201211_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapp',
            name='acchievemnt',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='course',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='dlicense',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='inquery',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='jobapp',
            name='skill',
        ),
        migrations.AddField(
            model_name='acchievemnts',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='closecontact',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='computerknowledge',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='courses',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='inqueries',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='lang',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
        migrations.AddField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
    ]
