# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-11 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20201211_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='clfy_bechalore',
            new_name='clfy_country',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='clfy_high_diplom',
            new_name='clfy_place',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='clfy_inter_diplom',
            new_name='clfy_type',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='clfy_master',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='clfy_other',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='clfy_phd',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='clfy_secondary',
        ),
        migrations.AddField(
            model_name='qualification',
            name='clfy_from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='qualification',
            name='clfy_graduate_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='qualification',
            name='clfy_name',
            field=models.CharField(blank=True, choices=[('s', 'Secondary'), ('id', 'Intermediate Diploma'), ('b', 'Bechalore'), ('hd', 'High Diploma'), ('m', 'Master'), ('phd', 'Phelosephy'), ('o', 'Other')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='clfy_to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
