# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-11 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20201211_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang',
            old_name='lang_lang_exam',
            new_name='lang_o_lang_exam',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_ar',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_en',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_other1',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_other2',
        ),
        migrations.AddField(
            model_name='lang',
            name='lang_type',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'english'), ('o', 'Other')], default='', max_length=200),
        ),
    ]
