# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20201211_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='clfy_country',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_name',
            field=models.CharField(blank=True, choices=[('s', 'Secondary'), ('id', 'Intermediate Diploma'), ('b', 'Bechalore'), ('hd', 'High Diploma'), ('m', 'Master'), ('phd', 'Phelosephy'), ('o', 'Other')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_place',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
