# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-15 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20201215_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_ex_type', models.CharField(choices=[('T', 'Toefel'), ('en', 'english'), ('o', 'Other')], default='', max_length=200, null=True)),
                ('lang_score', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courses_1',
            new_name='cert_type',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courses_2',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courses_3',
            new_name='courses_Name',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='courses_4',
            new_name='interval',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_en_exam',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_o_lang_exam',
        ),
        migrations.RemoveField(
            model_name='lang',
            name='lang_toefl',
        ),
        migrations.AddField(
            model_name='courses',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='palce',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='score',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='ID_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='lang',
            name='conv_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lang',
            name='reading_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lang',
            name='writing_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='qualification',
            name='clfy_photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='langexam',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp'),
        ),
    ]
