# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20201215_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='fname'),
        ),
    ]
