# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-15 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20201215_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='Hobbies',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='الهوايات'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='وبتاريخ'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_issued_from',
            field=models.CharField(max_length=200, verbose_name='صادرة من'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_number',
            field=models.CharField(max_length=200, verbose_name='برقم'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_photo',
            field=models.ImageField(default='', upload_to='images/', verbose_name='صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_type',
            field=models.CharField(choices=[('ID', 'ID'), ('PS', 'Passport'), ('O', 'Other')], max_length=200, verbose_name='نوع الهوية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ ومحل '),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=200, null=True, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='email_other',
            field=models.EmailField(blank=True, default='', max_length=100, null=True, verbose_name='أخر'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='father_birth_place',
            field=models.CharField(max_length=200, verbose_name='مكان ميلاد الأب'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='father_name',
            field=models.CharField(max_length=200, verbose_name='اسم الأب'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='grandfather_name',
            field=models.CharField(max_length=200, verbose_name='اسم الجد'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='home_phone',
            field=models.CharField(blank=True, default='00967', max_length=200, null=True, verbose_name='رقم هاتف المنزل'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='mobile',
            field=models.CharField(max_length=200, verbose_name='رقم هاتفك المحمول'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='mobile_other',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم أخر'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='nationality',
            field=models.CharField(choices=[('Y', 'Yemeni'), ('O', 'Other')], max_length=200, verbose_name='الجنسية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_city',
            field=models.IntegerField(choices=[(1, 'Sanaa'), (2, 'Aden'), (3, 'IBB'), (4, 'Taiz'), (5, 'Thamar'), (6, 'Amran'), (7, 'Shabwa'), (8, 'Haja')], verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_district',
            field=models.CharField(default='', max_length=200, verbose_name='المديرية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_place',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان السكن الدائم'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_street',
            field=models.CharField(default='', max_length=200, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='اللقب:'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='telegram',
            field=models.CharField(blank=True, default='00967', max_length=200, null=True, verbose_name='حساب التليجرام'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='whatsapp',
            field=models.CharField(blank=True, default='00967', max_length=200, null=True, verbose_name='حساب واتساب'),
        ),
    ]
