# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-15 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20201215_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='clfy_ranking',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='التقدير العام'),
        ),
        migrations.AlterField(
            model_name='acchievemnts',
            name='details',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='اذكر باختصار أهم انجازاتك المهنية'),
        ),
        migrations.AlterField(
            model_name='acchievemnts',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_Name',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_job',
            field=models.CharField(default='', max_length=200, verbose_name='العمل'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_other_phone',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم أخر'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_phone',
            field=models.CharField(default='', max_length=200, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_relation',
            field=models.CharField(default='', max_length=200, verbose_name='نوع القرابة'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_residence_place',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان السكن'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='close_contacts_work_address',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان العمل'),
        ),
        migrations.AlterField(
            model_name='closecontact',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='computerknowledge',
            name='computer_knowledge',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل تستطيع استخدام الحاسب الآلي'),
        ),
        migrations.AlterField(
            model_name='computerknowledge',
            name='internet_knowledge',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل تستطيع استخدام البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='cert_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نوع الشهادة'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='country',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='courses_Name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='اسم الدورة'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الفترة إلى'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='interval',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عدد الساعات'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='palce',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الجهة المنفذة للدورة'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='score',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التقدير العام'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الفترة من'),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='driving_license',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل تستطيع قيادة السيارات وسائل النقل'),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='driving_license_active',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20, verbose_name='هل لديك رخصة قيادة سارية المفعول'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='allowance',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='العلاوات الأخرى بالتفصيل'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ انتهاء الخدمة'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_service_reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='أسباب انتهاء الخدمة'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='تاريخ الالتحاق بالعمل'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='last_supervison',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='اسم أخر رئيس مباشر عليك'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='last_supervison_phone',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم هاتفه'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='أسم المنشأة وعنوانها'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position1_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position1_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 1'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position1_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position2_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position2_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 2'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position2_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position3_from_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position3_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='مسميات الوظائف التي شغلتها 3'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position3_to_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='الى تاريخ'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resp_desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='وصف مختصر للمهام والواجبات والمسؤوليات لأخر وظيفة'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary_begin',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الراتب الشهري عند التوظيف'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='salary_end',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='الراتب الشهري عند انتهاء الخدمة'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_accept_w_place',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=200, verbose_name='وهل تقبل العمل في محافظة إذا طلب منك ذلك'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_cust_contact',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Sometimes')], default='', max_length=20, verbose_name='هل سبق وكانت طبيعة عملك تتطلب التعامل مع العملاء؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_explain',
            field=models.CharField(default='', max_length=200, verbose_name='لماذا ترغب في العمل لدى البنك المركزي اليمني؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_favor_w_place',
            field=models.IntegerField(choices=[(1, 'عمران'), (2, 'محافظة'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], default='0', verbose_name='ماهي المحافظة التي تفضل العمل فيها، بحكم تواجد السكن الأصلي لك؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_loan',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20, verbose_name='هل عليك قروض أو ديون أو مشاكل مادية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_long_term_disease',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل تعاني من أي مشاكل صحية أو نفسية أو أمراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_surgery',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل سبق ان أجريت لك أي عملية جراحية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('D', 'Not Now')], default='', max_length=20, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training_detail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة ب )نعم( نرجو تحديد هذه الدورات'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ الميلاد '),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='photo',
            field=models.ImageField(default='', upload_to='images/', verbose_name='صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_favorite_hours',
            field=models.CharField(default='', max_length=200, verbose_name='ساعات العمل التي تفضلها'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_fit_name',
            field=models.CharField(default='', max_length=200, verbose_name='الوظيفة التي تقدمت لشغلها و التي تتناسب مع مؤهلك'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_in_bank_relat',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل لديك أقارب في البنك المركزي اليمني'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_know_channel',
            field=models.CharField(default='', max_length=200, verbose_name='كيف علمت بهذه الوظيفة'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_least_income',
            field=models.CharField(default='', max_length=200, verbose_name='ما هو أقل دخل شهري يمكنك العمل به شاملاً جميع البدلات'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_non_announcement',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حدد وضيفة أخرى معلن عنها وترغب بالتقدم لها وتعتقد أنك مؤهل لها عدا الوظيفة المتقدم لها'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_out_bank_relat',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='هل لديك أقارب في الجهات ذات الصلة بالبنك'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_salary_exp',
            field=models.CharField(default='', max_length=200, verbose_name='الراتب والمزايا المتوقعة'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='conv_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, verbose_name='محادثة'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='lang_type',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'english'), ('o', 'Other')], default='', max_length=200, verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='reading_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, verbose_name='قراءة'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='writing_level',
            field=models.CharField(choices=[('e', 'ممتاز'), ('vg', 'جيد جد ا'), ('g', 'جيد'), ('ac', 'متوسط'), ('w', 'ضعيف')], default='', max_length=200, verbose_name='كتابة'),
        ),
        migrations.AlterField(
            model_name='langexam',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.JobApp', verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='langexam',
            name='lang_ex_type',
            field=models.CharField(choices=[('T', 'Toefel'), ('en', 'english'), ('o', 'Other')], default='', max_length=200, null=True, verbose_name='هل سبق وتقدمت لامتحان اللغة'),
        ),
        migrations.AlterField(
            model_name='langexam',
            name='lang_score',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التقدير العام'),
        ),
        migrations.AlterField(
            model_name='position',
            name='from_date',
            field=models.DateField(default=datetime.date.today, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='position',
            name='to_date',
            field=models.DateField(default=datetime.date.today, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_country',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_from_date',
            field=models.DateField(default=datetime.date.today, verbose_name='من'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_graduate_date',
            field=models.DateField(default=datetime.date.today, verbose_name='سنة التخرج'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_name',
            field=models.CharField(blank=True, choices=[('s', 'Secondary'), ('id', 'Intermediate Diploma'), ('b', 'Bechalore'), ('hd', 'High Diploma'), ('m', 'Master'), ('phd', 'Phelosephy'), ('o', 'Other')], default='', max_length=100, null=True, verbose_name='المؤهل الدراسي'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_photo',
            field=models.ImageField(default='', upload_to='images/', verbose_name='صورة المؤهل'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_place',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='اسم المدرسة/الجامعة'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_to_date',
            field=models.DateField(default=datetime.date.today, verbose_name='إلى'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_type',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='نوع الشهادة'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='الرجاء تحديد أي مهارات/قدرات خاصة بك'),
        ),
    ]
