# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-16 12:26
from __future__ import unicode_literals

import application.models
import application.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_auto_20201215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='ID_photo',
            field=models.ImageField(default='', upload_to=application.models.JobApp.user_directory_path, validators=[application.validators.validate_file_extension], verbose_name='صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='رقم هاتف المنزل'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='photo',
            field=models.ImageField(default='', upload_to=application.models.JobApp.user_directory_path, validators=[application.validators.validate_file_extension], verbose_name='صورة شخصية'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حساب التليجرام'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='حساب واتساب'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='clfy_photo',
            field=models.FileField(default='', upload_to=application.models.Qualification.user_directory_path, validators=[django.core.validators.MaxValueValidator(5000, 'max size is 5M'), application.validators.validate_file_extension], verbose_name='وثيقة المؤهل'),
        ),
    ]
