# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-16 12:35
from __future__ import unicode_literals

import application.models
import application.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20201216_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='clfy_photo',
            field=models.FileField(default='', upload_to=application.models.Qualification.user_directory_path, validators=[application.validators.validate_file_extension], verbose_name='وثيقة المؤهل'),
        ),
    ]
