# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20201216_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='user',
        ),
    ]
