# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-20 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20201220_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapp',
            options={'verbose_name': 'استمارة طلب توظيف'},
        ),
    ]
