# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20201223_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='ID_issue_date',
            field=models.DateField(verbose_name='وبتاريخ'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='birth_date',
            field=models.DateField(default=datetime.date(2020, 12, 23), verbose_name='تاريخ الميلاد '),
        ),
    ]
