# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_auto_20201223_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerknowledge',
            name='computer_knowledge_details',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نرجو تحديد أسماء البرامج'),
        ),
        migrations.AddField(
            model_name='computerknowledge',
            name='internet_knowledge_details',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نرجو تحديد أنواع البريد'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='birth_place',
            field=models.CharField(default=1, max_length=200, verbose_name='مكان الميلاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapp',
            name='childs_number',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='عدد الأولاد'),
        ),
        migrations.AddField(
            model_name='jobapp',
            name='marital_status',
            field=models.CharField(choices=[('S', 'عازب'), ('M', 'متزوج'), ('O', 'أخرى')], default=1, max_length=200, verbose_name='الحالة الإجتماعية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='cert_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_favor_w_place',
            field=models.IntegerField(choices=[(0, 'الأمانة'), (1, 'عمران'), (2, 'محافظة صنعاء'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], default='0', verbose_name='ماهي المحافظة التي تفضل العمل فيها، بحكم تواجد السكن الأصلي لك؟'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='ID_issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='وبتاريخ'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ الميلاد '),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A1', 'A+'), ('A2', 'A-'), ('B1', 'B+'), ('B2', 'B-'), ('AB1', 'AB+'), ('AB2', 'AB-'), ('O1', 'O+'), ('O2', 'O-')], max_length=200, null=True, verbose_name='فصيلة الدم'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_city',
            field=models.IntegerField(choices=[(0, 'الأمانة'), (1, 'عمران'), (2, 'محافظة صنعاء'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_district',
            field=models.CharField(default='', max_length=200, verbose_name='بجوار أو بالقرب '),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_place',
            field=models.CharField(db_column=False, editable=False, max_length=100, null=True, verbose_name='عنوان السكن الدائم'),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='residence_street',
            field=models.CharField(default='', max_length=200, verbose_name='الحي أو الشارع'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='lang_type',
            field=models.CharField(choices=[('en', 'الإنجليزية'), ('ar', 'العربية'), ('o', 'اخرى')], default='', max_length=200, verbose_name='اللغة'),
        ),
    ]
