# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20201223_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='inqueries',
            name='inq_long_term_disease_detail',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='في حالة الإجابة ب )نعم( نرجو ذكرها'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_cust_contact',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل سبق وكانت طبيعة عملك تتطلب التعامل مع العملاء؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_long_term_disease',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تعاني من أي مشاكل صحية أو نفسية أو أمراض مزمنة'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training',
            field=models.CharField(choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك'),
        ),
    ]
