# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20201223_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='driving_license',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, null=True, verbose_name='هل تستطيع قيادة السيارات وسائل النقل'),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='driving_license_active',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, null=True, verbose_name='هل لديك رخصة قيادة سارية المفعول'),
        ),
    ]
