# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20201223_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='inq_cust_contact',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل سبق وكانت طبيعة عملك تتطلب التعامل مع العملاء؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_favor_w_place',
            field=models.IntegerField(blank=True, choices=[(23, 'الأمانة'), (1, 'عمران'), (2, 'محافظة صنعاء'), (3, 'الحديدة'), (4, 'الجوف'), (5, 'المحويت'), (6, 'أمانة'), (7, 'ذمار'), (8, 'حجة'), (9, 'إب'), (10, 'مأرب'), (11, 'محافظة'), (12, 'صعدة'), (13, 'صنعاء'), (14, 'تعز'), (15, 'عدن'), (16, 'أبين'), (17, 'محافظة'), (18, 'المهرة'), (19, 'حضرموت'), (20, 'أرخبيل'), (21, 'لحج'), (22, 'شبوة')], default='0', verbose_name='ماهي المحافظة التي تفضل العمل فيها، بحكم تواجد السكن الأصلي لك؟'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_loan',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل عليك قروض أو ديون أو مشاكل مادية'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_training',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=20, verbose_name='هل ترغب في الحصول على دورات تدريبية في مجال عملك'),
        ),
    ]
