# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-12-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_auto_20201223_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inqueries',
            name='inq_accept_w_place',
            field=models.CharField(blank=True, choices=[('Y', 'نعم'), ('N', 'لا')], default='', max_length=200, verbose_name='وهل تقبل العمل في محافظة إذا طلب منك ذلك'),
        ),
        migrations.AlterField(
            model_name='inqueries',
            name='inq_explain',
            field=models.TextField(default='', max_length=200, verbose_name='لماذا ترغب في العمل لدى البنك المركزي اليمني؟'),
        ),
    ]
